# Generated by Django 4.2 on 2024-08-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', "To'langan"), ('unpaid', 'Unpaid')], default='unpaid', max_length=16, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('payme', 'Payme'), ('click', 'Click'), ('terminal', 'Terminal'), ('other', 'Boshqa')], max_length=16, null=True, verbose_name="To'lov turi"),
        ),
    ]
