# Generated by Django 4.2 on 2024-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='Agentmi ?'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqam'),
        ),
    ]
