# Generated by Django 4.2 on 2024-08-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': "Biz bilan bog'laning", 'verbose_name_plural': "Biz bilan bog'laning"},
        ),
    ]
