# Generated by Django 4.2 on 2024-08-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Menedjer', 'verbose_name_plural': 'Menedjerlar'},
        ),
    ]
