# Generated by Django 4.2 on 2024-08-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
    ]
