# Generated by Django 4.2 on 2024-08-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
    ]
