# Generated by Django 4.2 on 2024-08-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.IntegerField(default=0, verbose_name='Narxi (USD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_uzs',
            field=models.IntegerField(default=0, verbose_name="Narxi (so'm)"),
        ),
    ]
