# Generated by Django 4.2 on 2024-08-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_product_price_product_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Ommabop mahsulot'),
        ),
    ]
