# Generated by Django 4.2 on 2024-08-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_product_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
    ]
