# Generated by Django 4.2 on 2024-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name="Narxi (so'm) Majburiy"),
        ),
    ]
