# Generated by Django 4.2 on 2024-08-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
