# Generated by Django 4.2 on 2024-09-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='category',
            field=models.CharField(blank=True, choices=[('a_class', 'A'), ('b_class', 'B'), ('c_class', 'C')], max_length=12, null=True, verbose_name='Категория клиента'),
        ),
    ]
