# Generated by Django 4.2 on 2024-09-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_area_telegramuser_territory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='territory',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='territory',
            field=models.ManyToManyField(blank=True, null=True, to='bot.area', verbose_name='Территория'),
        ),
    ]
