# Generated by Django 4.2 on 2024-09-02 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_telegramuser_territory_telegramuser_territory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория клиента',
                'verbose_name_plural': 'Категории клиентов',
            },
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.clientcategory', verbose_name='Категория клиента'),
        ),
    ]
