# Generated by Django 4.2 on 2024-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_clientcategory_alter_telegramuser_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_usd',
            field=models.IntegerField(default=0, verbose_name='Цена USD'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_uzs',
            field=models.IntegerField(default=0, verbose_name='Цена sum'),
        ),
    ]
