# Generated by Django 4.2 on 2024-09-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_remove_orderitem_price_orderitem_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bot.telegramuser', verbose_name='Agent'),
        ),
    ]
