# Generated by Django 4.2 on 2024-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_orderitem_price_usd_alter_orderitem_price_uzs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.CharField(max_length=255, verbose_name='Число'),
        ),
    ]
