# Generated by Django 4.2 on 2024-09-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_remove_product_price'),
        ('bot', '0021_alter_orderitem_qty'),
    ]

    operations = [
    ]
