# Generated by Django 4.2 on 2024-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_alter_orderitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcategory',
            name='action',
            field=models.CharField(choices=[('increase', "Qo'shish"), ('decrease', 'Ayirish')], default='increase', max_length=255, verbose_name='Добавить/вычесть цену'),
        ),
        migrations.AddField(
            model_name='clientcategory',
            name='amount_usd',
            field=models.CharField(default=0, max_length=255, verbose_name='Сумма USD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcategory',
            name='amount_uzs',
            field=models.CharField(default=0, max_length=255, verbose_name='Сумма UZS'),
            preserve_default=False,
        ),
    ]
