# Generated by Django 4.2 on 2024-09-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_clientcategory_action_clientcategory_amount_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcategory',
            name='action',
            field=models.CharField(choices=[('increase', 'Добавлять'), ('decrease', 'Вычесть')], default='increase', max_length=255, verbose_name='Добавить/вычесть цену'),
        ),
    ]
