# Generated by Django 4.2 on 2024-09-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_clientcategory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(default=0, verbose_name='Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs',
            field=models.FloatField(default=0, verbose_name='Цена (сум)'),
        ),
    ]
