# Generated by Django 4.2 on 2024-09-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_merge_20240902_0628'),
        ('bot', '0024_alter_product_price_usd_alter_product_price_uzs'),
    ]

    operations = [
    ]
