# Generated by Django 4.2 on 2024-09-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_alter_product_price_usd_alter_product_price_uzs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_path',
            field=models.URLField(blank=True, null=True, verbose_name='Место доставки'),
        ),
    ]
