# Generated by Django 4.2 on 2024-09-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_merge_20240906_1719'),
        ('bot', '0025_order_location_path'),
    ]

    operations = [
    ]
