# Generated by Django 4.2 on 2024-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_telegramuser_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('payme', 'Payme'), ('click', 'Click'), ('terminal', 'Терминал'), ('transfer', 'Перечисления'), ('other', 'Другой')], max_length=16, null=True, verbose_name='Тип платежа'),
        ),
    ]
