# Generated by Django 4.2 on 2024-09-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Он активен?'),
        ),
    ]
