# Generated by Django 4.2 on 2024-09-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_telegramuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd_a',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (долл. США) A'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd_b',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (долл. США) B'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd_c',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (долл. США) C'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_uzs_a',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (сум) A'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_uzs_b',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (сум) B'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_uzs_c',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (сум) C'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена (сум)'),
        ),
    ]
