# Generated by Django 4.2 on 2024-09-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_merge_20240908_0603'),
        ('bot', '0028_telegramuser_is_active'),
    ]

    operations = [
    ]
