# Generated by Django 4.2 on 2024-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_product_price_usd_a_product_price_usd_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=255, null=True, verbose_name='Категория клиента'),
        ),
    ]
