# Generated by Django 4.2 on 2024-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_alter_telegramuser_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd_a',
            field=models.FloatField(default=0, verbose_name='Цена (долл. США) A'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_b',
            field=models.FloatField(default=0, verbose_name='Цена (долл. США) B'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_c',
            field=models.FloatField(default=0, verbose_name='Цена (долл. США) C'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_a',
            field=models.FloatField(default=0, verbose_name='Цена (сум) A'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_b',
            field=models.FloatField(default=0, verbose_name='Цена (сум) B'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_c',
            field=models.FloatField(default=0, verbose_name='Цена (сум) C'),
        ),
    ]
