# Generated by Django 4.2 on 2024-09-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_merge_20240910_0424'),
        ('bot', '0031_alter_product_price_usd_a_alter_product_price_usd_b_and_more'),
    ]

    operations = [
    ]
