# Generated by Django 4.2 on 2024-09-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_alter_product_price_usd_a_alter_product_price_usd_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Новый'), ('approved_by_account', 'Аттестовано бухгалтером'), ('approved_by_director', 'Утверждено директором'), ('approved_by_storekeeper', 'Подтверждено кладовщиком'), ('cancelled', 'Отменено')], default='pending', max_length=24, verbose_name='Статус заказа'),
        ),
    ]
