# Generated by Django 4.2 on 2024-09-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_alter_order_status'),
        ('bot', '0032_merge_20240911_2227'),
    ]

    operations = [
    ]
