# Generated by Django 4.2 on 2024-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set_amount',
            field=models.FloatField(default=1, verbose_name='Количество в блоке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
    ]
