# Generated by Django 4.2 on 2024-09-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_product_set_amount_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='set_amount',
            field=models.CharField(default='0', max_length=255, verbose_name='блок'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='limit',
            field=models.FloatField(default=0, verbose_name='Сумма лимит (UZS)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.CharField(max_length=255, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='set_amount',
            field=models.FloatField(default=0, verbose_name='Количество в блоке'),
        ),
    ]
