# Generated by Django 4.2 on 2024-09-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_orderitem_product_in_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
