# Generated by Django 4.2 on 2024-09-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_merge_20240914_1333'),
        ('bot', '0035_orderitem_product_in_set'),
    ]

    operations = [
    ]
