# Generated by Django 4.2 on 2024-09-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_merge_20240916_0711'),
        ('bot', '0036_orderitem_product_id'),
    ]

    operations = [
    ]
