# Generated by Django 4.2 on 2024-09-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_product_price_uzs_d_alter_product_price_usd_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd_a',
            field=models.FloatField(default=0, verbose_name='Стандарт Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_b',
            field=models.FloatField(default=0, verbose_name='-4% Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_c',
            field=models.FloatField(default=0, verbose_name='Хорека Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_a',
            field=models.FloatField(default=0, verbose_name='Стандарт Цена (сум)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_b',
            field=models.FloatField(default=0, verbose_name='-4% Цена (сум)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_c',
            field=models.FloatField(default=0, verbose_name='Хорека Цена (сум)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_d',
            field=models.FloatField(default=0, verbose_name='Оптовик Цена (сум)'),
        ),
    ]
