# Generated by Django 4.2 on 2024-09-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_merge_20240916_0728'),
        ('bot', '0038_alter_product_price_usd_a_alter_product_price_usd_b_and_more'),
    ]

    operations = [
    ]
