# Generated by Django 4.2 on 2024-09-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_merge_20240919_0009'),
        ('bot', '0039_telegramuser_address_telegramuser_contract_id_and_more'),
    ]

    operations = [
    ]
