# Generated by Django 4.2 on 2024-09-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_alter_telegramuser_last_name'),
        ('bot', '0040_merge_20240925_2221'),
    ]

    operations = [
    ]
