# Generated by Django 4.2 on 2024-09-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_alter_telegramuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
