# Generated by Django 4.2 on 2024-09-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_alter_telegramuser_telegram_id'),
        ('bot', '0041_merge_20240925_2225'),
    ]

    operations = [
    ]
