# Generated by Django 4.2 on 2024-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd_d',
            field=models.FloatField(default=0, editable=False, verbose_name='Оптовик Цена (долл. США)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd_e',
            field=models.FloatField(default=0, editable=False, verbose_name='-4% Цена (долл. США)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_uzs_e',
            field=models.FloatField(default=0, verbose_name='-4% Цена (сум)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_a',
            field=models.FloatField(default=0, editable=False, verbose_name='Стандарт Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_b',
            field=models.FloatField(default=0, editable=False, verbose_name='-4% Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_c',
            field=models.FloatField(default=0, editable=False, verbose_name='Хорека Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'Стандарт'), ('b', '-4%'), ('c', 'Хорека'), ('d', 'Оптовик'), ('e', '-2%')], max_length=255, null=True, verbose_name='Категория клиента'),
        ),
    ]
