# Generated by Django 4.2 on 2024-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_product_price_usd_d_product_price_usd_e_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd_e',
            field=models.FloatField(default=0, editable=False, verbose_name='-2% Цена (долл. США)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs_e',
            field=models.FloatField(default=0, verbose_name='-2% Цена (сум)'),
        ),
    ]
