# Generated by Django 4.2 on 2024-09-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_merge_20240925_2329'),
        ('bot', '0043_alter_product_price_usd_e_alter_product_price_uzs_e'),
    ]

    operations = [
    ]
