# Generated by Django 4.2 on 2024-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0043_alter_product_price_usd_e_alter_product_price_uzs_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_usd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена USD'),
        ),
    ]
