# Generated by Django 4.2 on 2024-09-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0044_alter_orderitem_price_usd'),
        ('bot', '0044_merge_20240927_2214'),
    ]

    operations = [
    ]
