# Generated by Django 4.2 on 2024-09-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0044_alter_orderitem_price_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория товаров'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанные продукты', 'verbose_name_plural': 'Заказанные продукты'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_usd',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Цена USD'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_in_set',
            field=models.FloatField(default=0, verbose_name='Количество в Блок'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='set_amount',
            field=models.CharField(default='0', max_length=255, verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='set_amount',
            field=models.FloatField(default=0, verbose_name='Количество в блоке'),
        ),
    ]
