# Generated by Django 4.2 on 2024-09-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_alter_category_options_alter_orderitem_options_and_more'),
        ('bot', '0045_merge_20240928_1139'),
    ]

    operations = [
    ]
