# Generated by Django 4.2 on 2024-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0046_merge_20240929_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_accountant_confirm',
            field=models.BooleanField(default=False, verbose_name='Бухгалтер подтвердил?'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_director_confirm',
            field=models.BooleanField(default=False, verbose_name='Директор подтвердил?'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_storekeeper_confirm',
            field=models.BooleanField(default=False, verbose_name='Кладовщик подтвердил?'),
        ),
    ]
