# Generated by Django 4.2 on 2025-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0047_order_comment_order_is_accountant_confirm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архивы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bot.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='accountant_cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отказа бухгалтером'),
        ),
        migrations.AddField(
            model_name='order',
            name='director_cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отказа директором'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_accountant_cancel',
            field=models.BooleanField(default=False, verbose_name='Бухгалтер отменил?'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_director_cancel',
            field=models.BooleanField(default=False, verbose_name='Директор отменил?'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_storekeeper_cancel',
            field=models.BooleanField(default=False, verbose_name='Кладовщик отменил?'),
        ),
        migrations.AddField(
            model_name='order',
            name='storekeeper_cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отказа кладовщика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Новый'), ('approved_by_account', 'Аттестовано бухгалтером'), ('approved_by_director', 'Утверждено директором'), ('approved_by_storekeeper', 'Подтверждено кладовщиком'), ('canceled_by_account', 'Отказано бухгалтером'), ('canceled_by_director', 'Отказано директором'), ('canceled_by_storekeeper', 'Отказано кладовщиком'), ('cancelled', 'Отменено')], default='pending', max_length=24, verbose_name='Статус заказа'),
        ),
    ]
