# Generated by Django 4.2 on 2025-01-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0048_archiveorder_order_accountant_cancel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rop_cancel',
            field=models.BooleanField(default=False, verbose_name='Руководитель отдела продаж отменил?'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_rop_confirm',
            field=models.BooleanField(default=False, verbose_name='Руководитель отдела продаж подтвердил?'),
        ),
        migrations.AddField(
            model_name='order',
            name='rop_approve_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время утверждения руководителем отдела продаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='rop_cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отказа руководителя отдела продаж'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('rop', 'Руководитель отдел продаж'), ('director', 'Директор'), ('accountant', 'Бухгалтер'), ('storekeeper', 'Заведующий складом')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Новый'), ('approved_by_rop', 'Согласовано руководителем отдела продаж'), ('approved_by_account', 'Аттестовано бухгалтером'), ('approved_by_director', 'Утверждено директором'), ('approved_by_storekeeper', 'Подтверждено кладовщиком'), ('canceled_by_rop', 'Отказано руководителем отдела продаж'), ('canceled_by_account', 'Отказано бухгалтером'), ('canceled_by_director', 'Отказано директором'), ('canceled_by_storekeeper', 'Отказано кладовщиком'), ('cancelled', 'Отменено')], default='pending', max_length=24, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='storekeeper_cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отказа кладовщиком'),
        ),
    ]
