# Generated by Django 4.2 on 2025-06-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclatura_id_1c', models.CharField(max_length=64)),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('client_name', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_tin', models.CharField(blank=True, max_length=20, null=True)),
                ('contract', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('sent_successfully', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nomenclature',
                'verbose_name_plural': 'Nomenclatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('catalog_code', models.CharField(blank=True, max_length=32, null=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('package_code', models.CharField(blank=True, max_length=32, null=True)),
                ('code1c', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='integrations.nomenclature')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
