# Generated by Django 4.2 on 2025-06-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tin', models.CharField(max_length=20, unique=True)),
                ('cr_on', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ContrAgent',
                'verbose_name_plural': 'ContrAgents',
                'ordering': ['-cr_on'],
            },
        ),
        migrations.RenameField(
            model_name='nomenclature',
            old_name='nomenclatura_id_1c',
            new_name='external_id',
        ),
        migrations.CreateModel(
            name='ContrAgentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('contr_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='integrations.contragent')),
            ],
            options={
                'verbose_name': 'ContrAgent Balance',
                'verbose_name_plural': 'ContrAgent Balances',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contragent',
            index=models.Index(fields=['tin'], name='integration_tin_2c3739_idx'),
        ),
    ]
