# Generated by Django 4.2 on 2025-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_contragent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='baseSumma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
